### ISSUE TITLE
Updates [TO-DO]

### ISSUE THREAD

**Issue by 64J0** [64J0/pokemon-angular-ilia#1]
- [ ] Use an store to keep the global state of the application ([NGRX](https://www.youtube.com/watch?v=BobNwRgz6Uw&ab_channel=MatheusCastiglioni));
- [ ] Create a button to get back from the details page;
- [ ] Create a button to refresh the pokemon list in home page;
- [ ] Create an input field so the user can search a pokemon by its name in the home page;
- [ ] Implement the modal with more details about the pokemon that should be opened when an user clicks in the attacks section in details page;
- [ ] Upgrade the use of Sass variables defined in app/styles.scss;
- [ ] Enhance the README.md with a more customized explanation about the choices made in the project;
- [ ] Deploy the application in production;
- [ ] Enhance the design of the application;

**Comment by 64J0** [comment]
That's it, now I need to sleep... Tomorrow maybe I'll implement the store just to finish this project.

Some aspects couldn't be treated in this project because I don't have the knowledge to implement those solutions in the available time, like the internationalization and the features related to the automated test with Angular.

But as the first Angular project that has been made in two nights, I think that it's good.

**Comment by 64J0** [comment]
As a new task, I've been asked to implement some unit tests. In my research, I have found that Angular uses Jasmine as the framework to write and run tests so I'll keep studying and try to implement this feature.

**Comment by 64J0** [comment]
That's it, today I have implemented my first tests with **Angular** using **Jasmine** with **Karma**. Also, I've learned how to use *debugger* to enhance the power of debugging with Chrome using the *Sources* window in the *dev tools*.

**Comment by 64J0** [comment]
https://github.com/aisdigital/FrontEndChallenge/blob/master/README.md
